/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConcertBooking;

import javax.swing.JOptionPane;

/**
 *
 * @author b00687749
 */
public class ConcertUI extends javax.swing.JFrame {

    /**
     * Creates new form ConcertUI
     */
    public ConcertUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        newConcertButton = new javax.swing.JButton();
        setBronzePriceButton = new javax.swing.JButton();
        setPriceSliverButton = new javax.swing.JButton();
        setPriceGoldButton = new javax.swing.JButton();
        checkIfBookedButton = new javax.swing.JButton();
        bookingsByCustomerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        a1Button = new javax.swing.JButton();
        b1Button = new javax.swing.JButton();
        a2Button = new javax.swing.JButton();
        b2Button = new javax.swing.JButton();
        c1Button = new javax.swing.JButton();
        c2Button = new javax.swing.JButton();
        a4Button = new javax.swing.JButton();
        a5Button = new javax.swing.JButton();
        b3Button = new javax.swing.JButton();
        b4Button = new javax.swing.JButton();
        b5Button = new javax.swing.JButton();
        a3Button = new javax.swing.JButton();
        c4Button = new javax.swing.JButton();
        c5Button = new javax.swing.JButton();
        c3Button = new javax.swing.JButton();
        b6Button = new javax.swing.JButton();
        c9Button = new javax.swing.JButton();
        a7Button = new javax.swing.JButton();
        c10Button = new javax.swing.JButton();
        b7Button = new javax.swing.JButton();
        c8Button = new javax.swing.JButton();
        c6Button = new javax.swing.JButton();
        c7Button = new javax.swing.JButton();
        a9Button = new javax.swing.JButton();
        a10Button = new javax.swing.JButton();
        b8Button = new javax.swing.JButton();
        b9Button = new javax.swing.JButton();
        b10Button = new javax.swing.JButton();
        a6Button = new javax.swing.JButton();
        a8Button = new javax.swing.JButton();
        e1Button = new javax.swing.JButton();
        d2Button = new javax.swing.JButton();
        e2Button = new javax.swing.JButton();
        f1Button = new javax.swing.JButton();
        f2Button = new javax.swing.JButton();
        d4Button = new javax.swing.JButton();
        d5Button = new javax.swing.JButton();
        e3Button = new javax.swing.JButton();
        e4Button = new javax.swing.JButton();
        e5Button = new javax.swing.JButton();
        d1Button = new javax.swing.JButton();
        d3Button = new javax.swing.JButton();
        f4Button = new javax.swing.JButton();
        f5Button = new javax.swing.JButton();
        f3Button = new javax.swing.JButton();
        e6Button = new javax.swing.JButton();
        d7Button = new javax.swing.JButton();
        e7Button = new javax.swing.JButton();
        f6Button = new javax.swing.JButton();
        f7Button = new javax.swing.JButton();
        d9Button = new javax.swing.JButton();
        d10Button = new javax.swing.JButton();
        e8Button = new javax.swing.JButton();
        e9Button = new javax.swing.JButton();
        e10Button = new javax.swing.JButton();
        d6Button = new javax.swing.JButton();
        d8Button = new javax.swing.JButton();
        f9Button = new javax.swing.JButton();
        f10Button = new javax.swing.JButton();
        f8Button = new javax.swing.JButton();
        h1Button = new javax.swing.JButton();
        g2Button = new javax.swing.JButton();
        h2Button = new javax.swing.JButton();
        i1Button = new javax.swing.JButton();
        i2Button = new javax.swing.JButton();
        g4Button = new javax.swing.JButton();
        g5Button = new javax.swing.JButton();
        h3Button = new javax.swing.JButton();
        h4Button = new javax.swing.JButton();
        h5Button = new javax.swing.JButton();
        g1Button = new javax.swing.JButton();
        g3Button = new javax.swing.JButton();
        i4Button = new javax.swing.JButton();
        i5Button = new javax.swing.JButton();
        i3Button = new javax.swing.JButton();
        h6Button = new javax.swing.JButton();
        g7Button = new javax.swing.JButton();
        h7Button = new javax.swing.JButton();
        i6Button = new javax.swing.JButton();
        i7Button = new javax.swing.JButton();
        g9Button = new javax.swing.JButton();
        g10Button = new javax.swing.JButton();
        h8Button = new javax.swing.JButton();
        h9Button = new javax.swing.JButton();
        h10Button = new javax.swing.JButton();
        g6Button = new javax.swing.JButton();
        g8Button = new javax.swing.JButton();
        i9Button = new javax.swing.JButton();
        i10Button = new javax.swing.JButton();
        i8Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel5.setText("   1        2       3        4        5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newConcertButton.setText("New Concert");
        newConcertButton.setToolTipText("");
        newConcertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConcertButtonActionPerformed(evt);
            }
        });

        setBronzePriceButton.setText("Set Price Bronze");
        setBronzePriceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setBronzePriceButtonMouseClicked(evt);
            }
        });
        setBronzePriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBronzePriceButtonActionPerformed(evt);
            }
        });

        setPriceSliverButton.setText("Set Price Sliver");
        setPriceSliverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPriceSliverButtonMouseClicked(evt);
            }
        });

        setPriceGoldButton.setText("Set Price Gold");
        setPriceGoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPriceGoldButtonActionPerformed(evt);
            }
        });

        checkIfBookedButton.setText("Check if Booked");
        checkIfBookedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkIfBookedButtonMouseClicked(evt);
            }
        });

        bookingsByCustomerButton.setText("Bookings By Customer");
        bookingsByCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsByCustomerButtonMouseClicked(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        a1Button.setBackground(new java.awt.Color(255, 204, 0));
        a1Button.setForeground(new java.awt.Color(255, 204, 0));
        a1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ButtonActionPerformed(evt);
            }
        });

        b1Button.setBackground(new java.awt.Color(255, 204, 0));
        b1Button.setForeground(new java.awt.Color(255, 204, 0));

        a2Button.setBackground(new java.awt.Color(255, 204, 0));
        a2Button.setForeground(new java.awt.Color(255, 204, 0));

        b2Button.setBackground(new java.awt.Color(255, 204, 0));
        b2Button.setForeground(new java.awt.Color(255, 204, 0));

        c1Button.setBackground(new java.awt.Color(255, 204, 0));
        c1Button.setForeground(new java.awt.Color(255, 204, 0));

        c2Button.setBackground(new java.awt.Color(255, 204, 0));
        c2Button.setForeground(new java.awt.Color(255, 204, 0));

        a4Button.setBackground(new java.awt.Color(255, 204, 0));
        a4Button.setForeground(new java.awt.Color(255, 204, 0));

        a5Button.setBackground(new java.awt.Color(255, 204, 0));
        a5Button.setForeground(new java.awt.Color(255, 204, 0));

        b3Button.setBackground(new java.awt.Color(255, 204, 0));
        b3Button.setForeground(new java.awt.Color(255, 204, 0));

        b4Button.setBackground(new java.awt.Color(255, 204, 0));
        b4Button.setForeground(new java.awt.Color(255, 204, 0));

        b5Button.setBackground(new java.awt.Color(255, 204, 0));
        b5Button.setForeground(new java.awt.Color(255, 204, 0));

        a3Button.setBackground(new java.awt.Color(255, 204, 0));
        a3Button.setForeground(new java.awt.Color(255, 204, 0));
        a3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ButtonActionPerformed(evt);
            }
        });

        c4Button.setBackground(new java.awt.Color(255, 204, 0));
        c4Button.setForeground(new java.awt.Color(255, 204, 0));

        c5Button.setBackground(new java.awt.Color(255, 204, 0));
        c5Button.setForeground(new java.awt.Color(255, 204, 0));

        c3Button.setBackground(new java.awt.Color(255, 204, 0));
        c3Button.setForeground(new java.awt.Color(255, 204, 0));

        b6Button.setBackground(new java.awt.Color(255, 204, 0));
        b6Button.setForeground(new java.awt.Color(255, 204, 0));

        c9Button.setBackground(new java.awt.Color(255, 204, 0));
        c9Button.setForeground(new java.awt.Color(255, 204, 0));

        a7Button.setBackground(new java.awt.Color(255, 204, 0));
        a7Button.setForeground(new java.awt.Color(255, 204, 0));

        c10Button.setBackground(new java.awt.Color(255, 204, 0));
        c10Button.setForeground(new java.awt.Color(255, 204, 0));

        b7Button.setBackground(new java.awt.Color(255, 204, 0));
        b7Button.setForeground(new java.awt.Color(255, 204, 0));

        c8Button.setBackground(new java.awt.Color(255, 204, 0));
        c8Button.setForeground(new java.awt.Color(255, 204, 0));

        c6Button.setBackground(new java.awt.Color(255, 204, 0));
        c6Button.setForeground(new java.awt.Color(255, 204, 0));

        c7Button.setBackground(new java.awt.Color(255, 204, 0));
        c7Button.setForeground(new java.awt.Color(255, 204, 0));

        a9Button.setBackground(new java.awt.Color(255, 204, 0));
        a9Button.setForeground(new java.awt.Color(255, 204, 0));

        a10Button.setBackground(new java.awt.Color(255, 204, 0));
        a10Button.setForeground(new java.awt.Color(255, 204, 0));

        b8Button.setBackground(new java.awt.Color(255, 204, 0));
        b8Button.setForeground(new java.awt.Color(255, 204, 0));

        b9Button.setBackground(new java.awt.Color(255, 204, 0));
        b9Button.setForeground(new java.awt.Color(255, 204, 0));

        b10Button.setBackground(new java.awt.Color(255, 204, 0));
        b10Button.setForeground(new java.awt.Color(255, 204, 0));

        a6Button.setBackground(new java.awt.Color(255, 204, 0));
        a6Button.setForeground(new java.awt.Color(255, 204, 0));

        a8Button.setBackground(new java.awt.Color(255, 204, 0));
        a8Button.setForeground(new java.awt.Color(255, 204, 0));

        e1Button.setBackground(new java.awt.Color(204, 204, 204));
        e1Button.setForeground(new java.awt.Color(204, 204, 204));

        d2Button.setBackground(new java.awt.Color(204, 204, 204));
        d2Button.setForeground(new java.awt.Color(204, 204, 204));

        e2Button.setBackground(new java.awt.Color(204, 204, 204));
        e2Button.setForeground(new java.awt.Color(204, 204, 204));

        f1Button.setBackground(new java.awt.Color(204, 204, 204));
        f1Button.setForeground(new java.awt.Color(204, 204, 204));

        f2Button.setBackground(new java.awt.Color(204, 204, 204));
        f2Button.setForeground(new java.awt.Color(204, 204, 204));

        d4Button.setBackground(new java.awt.Color(204, 204, 204));
        d4Button.setForeground(new java.awt.Color(204, 204, 204));

        d5Button.setBackground(new java.awt.Color(204, 204, 204));
        d5Button.setForeground(new java.awt.Color(204, 204, 204));

        e3Button.setBackground(new java.awt.Color(204, 204, 204));
        e3Button.setForeground(new java.awt.Color(204, 204, 204));

        e4Button.setBackground(new java.awt.Color(204, 204, 204));
        e4Button.setForeground(new java.awt.Color(204, 204, 204));

        e5Button.setBackground(new java.awt.Color(204, 204, 204));
        e5Button.setForeground(new java.awt.Color(204, 204, 204));

        d1Button.setBackground(new java.awt.Color(204, 204, 204));
        d1Button.setForeground(new java.awt.Color(204, 204, 204));

        d3Button.setBackground(new java.awt.Color(204, 204, 204));
        d3Button.setForeground(new java.awt.Color(204, 204, 204));

        f4Button.setBackground(new java.awt.Color(204, 204, 204));
        f4Button.setForeground(new java.awt.Color(204, 204, 204));

        f5Button.setBackground(new java.awt.Color(204, 204, 204));
        f5Button.setForeground(new java.awt.Color(204, 204, 204));

        f3Button.setBackground(new java.awt.Color(204, 204, 204));
        f3Button.setForeground(new java.awt.Color(204, 204, 204));

        e6Button.setBackground(new java.awt.Color(204, 204, 204));
        e6Button.setForeground(new java.awt.Color(204, 204, 204));

        d7Button.setBackground(new java.awt.Color(204, 204, 204));
        d7Button.setForeground(new java.awt.Color(204, 204, 204));

        e7Button.setBackground(new java.awt.Color(204, 204, 204));
        e7Button.setForeground(new java.awt.Color(204, 204, 204));

        f6Button.setBackground(new java.awt.Color(204, 204, 204));
        f6Button.setForeground(new java.awt.Color(204, 204, 204));

        f7Button.setBackground(new java.awt.Color(204, 204, 204));
        f7Button.setForeground(new java.awt.Color(204, 204, 204));

        d9Button.setBackground(new java.awt.Color(204, 204, 204));
        d9Button.setForeground(new java.awt.Color(204, 204, 204));

        d10Button.setBackground(new java.awt.Color(204, 204, 204));
        d10Button.setForeground(new java.awt.Color(204, 204, 204));

        e8Button.setBackground(new java.awt.Color(204, 204, 204));
        e8Button.setForeground(new java.awt.Color(204, 204, 204));

        e9Button.setBackground(new java.awt.Color(204, 204, 204));
        e9Button.setForeground(new java.awt.Color(204, 204, 204));

        e10Button.setBackground(new java.awt.Color(204, 204, 204));
        e10Button.setForeground(new java.awt.Color(204, 204, 204));

        d6Button.setBackground(new java.awt.Color(204, 204, 204));
        d6Button.setForeground(new java.awt.Color(204, 204, 204));

        d8Button.setBackground(new java.awt.Color(204, 204, 204));
        d8Button.setForeground(new java.awt.Color(204, 204, 204));

        f9Button.setBackground(new java.awt.Color(204, 204, 204));
        f9Button.setForeground(new java.awt.Color(204, 204, 204));

        f10Button.setBackground(new java.awt.Color(204, 204, 204));
        f10Button.setForeground(new java.awt.Color(204, 204, 204));

        f8Button.setBackground(new java.awt.Color(204, 204, 204));
        f8Button.setForeground(new java.awt.Color(204, 204, 204));

        h1Button.setBackground(new java.awt.Color(102, 51, 0));
        h1Button.setForeground(new java.awt.Color(102, 51, 0));

        g2Button.setBackground(new java.awt.Color(102, 51, 0));
        g2Button.setForeground(new java.awt.Color(102, 51, 0));

        h2Button.setBackground(new java.awt.Color(102, 51, 0));
        h2Button.setForeground(new java.awt.Color(102, 51, 0));

        i1Button.setBackground(new java.awt.Color(102, 51, 0));
        i1Button.setForeground(new java.awt.Color(102, 51, 0));

        i2Button.setBackground(new java.awt.Color(102, 51, 0));
        i2Button.setForeground(new java.awt.Color(102, 51, 0));

        g4Button.setBackground(new java.awt.Color(102, 51, 0));
        g4Button.setForeground(new java.awt.Color(102, 51, 0));

        g5Button.setBackground(new java.awt.Color(102, 51, 0));
        g5Button.setForeground(new java.awt.Color(102, 51, 0));

        h3Button.setBackground(new java.awt.Color(102, 51, 0));
        h3Button.setForeground(new java.awt.Color(102, 51, 0));

        h4Button.setBackground(new java.awt.Color(102, 51, 0));
        h4Button.setForeground(new java.awt.Color(102, 51, 0));

        h5Button.setBackground(new java.awt.Color(102, 51, 0));
        h5Button.setForeground(new java.awt.Color(102, 51, 0));

        g1Button.setBackground(new java.awt.Color(102, 51, 0));
        g1Button.setForeground(new java.awt.Color(102, 51, 0));

        g3Button.setBackground(new java.awt.Color(102, 51, 0));
        g3Button.setForeground(new java.awt.Color(102, 51, 0));

        i4Button.setBackground(new java.awt.Color(102, 51, 0));
        i4Button.setForeground(new java.awt.Color(102, 51, 0));

        i5Button.setBackground(new java.awt.Color(102, 51, 0));
        i5Button.setForeground(new java.awt.Color(102, 51, 0));

        i3Button.setBackground(new java.awt.Color(102, 51, 0));
        i3Button.setForeground(new java.awt.Color(102, 51, 0));

        h6Button.setBackground(new java.awt.Color(102, 51, 0));
        h6Button.setForeground(new java.awt.Color(102, 51, 0));

        g7Button.setBackground(new java.awt.Color(102, 51, 0));
        g7Button.setForeground(new java.awt.Color(102, 51, 0));

        h7Button.setBackground(new java.awt.Color(102, 51, 0));
        h7Button.setForeground(new java.awt.Color(102, 51, 0));

        i6Button.setBackground(new java.awt.Color(102, 51, 0));
        i6Button.setForeground(new java.awt.Color(102, 51, 0));

        i7Button.setBackground(new java.awt.Color(102, 51, 0));
        i7Button.setForeground(new java.awt.Color(102, 51, 0));

        g9Button.setBackground(new java.awt.Color(102, 51, 0));
        g9Button.setForeground(new java.awt.Color(102, 51, 0));

        g10Button.setBackground(new java.awt.Color(102, 51, 0));
        g10Button.setForeground(new java.awt.Color(102, 51, 0));

        h8Button.setBackground(new java.awt.Color(102, 51, 0));
        h8Button.setForeground(new java.awt.Color(102, 51, 0));

        h9Button.setBackground(new java.awt.Color(102, 51, 0));
        h9Button.setForeground(new java.awt.Color(102, 51, 0));

        h10Button.setBackground(new java.awt.Color(102, 51, 0));
        h10Button.setForeground(new java.awt.Color(102, 51, 0));

        g6Button.setBackground(new java.awt.Color(102, 51, 0));
        g6Button.setForeground(new java.awt.Color(102, 51, 0));

        g8Button.setBackground(new java.awt.Color(102, 51, 0));
        g8Button.setForeground(new java.awt.Color(102, 51, 0));

        i9Button.setBackground(new java.awt.Color(102, 51, 0));
        i9Button.setForeground(new java.awt.Color(102, 51, 0));
        i9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i9ButtonActionPerformed(evt);
            }
        });

        i10Button.setBackground(new java.awt.Color(102, 51, 0));
        i10Button.setForeground(new java.awt.Color(102, 51, 0));

        i8Button.setBackground(new java.awt.Color(102, 51, 0));
        i8Button.setForeground(new java.awt.Color(102, 51, 0));

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));

        jLabel2.setText("Fire Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 51));

        jLabel3.setText("Fire Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setText("Stage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel4.setText("   1        2       3        4        5");

        jLabel6.setText("   6        7       8        9       10");

        jLabel7.setText("A");

        jLabel8.setText("B");

        jLabel9.setText("C");

        jLabel10.setText("D");

        jLabel11.setText("E");

        jLabel12.setText("F");

        jLabel13.setText("G");

        jLabel14.setText("H");

        jLabel15.setText("I");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newConcertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setBronzePriceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setPriceSliverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setPriceGoldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkIfBookedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingsByCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(165, 165, 165)
                                                            .addComponent(jLabel7))
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(g2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(i2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(f1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(f6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(g7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(i7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newConcertButton)
                    .addComponent(setBronzePriceButton)
                    .addComponent(setPriceSliverButton)
                    .addComponent(setPriceGoldButton)
                    .addComponent(checkIfBookedButton)
                    .addComponent(bookingsByCustomerButton)
                    .addComponent(exitButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(d1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(e1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(f1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel12)))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(g1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(h1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(i1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel14)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newConcertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConcertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newConcertButtonActionPerformed

    private void i9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i9ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i9ButtonActionPerformed

    private void a1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ButtonActionPerformed

    private void setBronzePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBronzePriceButtonActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_setBronzePriceButtonActionPerformed

    private void setBronzePriceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setBronzePriceButtonMouseClicked

        String bronzePrice = JOptionPane.showInputDialog(null, "Set Price For Bronze Seating:");
JOptionPane.showMessageDialog(null, "The Price Has been set to £" + bronzePrice);
         // TODO add your handling code here:
    }//GEN-LAST:event_setBronzePriceButtonMouseClicked

    private void setPriceSliverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPriceSliverButtonMouseClicked
String sliverPrice = JOptionPane.showInputDialog(null, "Set Price For Sliver Seating:");
JOptionPane.showMessageDialog(null, "The Price Has been set to £" + sliverPrice);
           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceSliverButtonMouseClicked

    private void setPriceGoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPriceGoldButtonActionPerformed
String goldPrice = JOptionPane.showInputDialog(null, "Set Price For Gold Seating:");
JOptionPane.showMessageDialog(null, "The Price Has been set to £" + goldPrice);
           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceGoldButtonActionPerformed

    private void checkIfBookedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkIfBookedButtonMouseClicked
      String checkIfBooked = JOptionPane.showInputDialog(null, "Enter the Seat You Would Like To Check");
//ADD  AN IF SATEMENT USING CHECKIFBOOKED TO RETURN A RESULT
       // TODO add your handling code here:
    }//GEN-LAST:event_checkIfBookedButtonMouseClicked

    private void bookingsByCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsByCustomerButtonMouseClicked
      String checkIfCustomerHasBookings = JOptionPane.showInputDialog(null, "Enter a Customer Name");
//ADD A FOR SATEMENT USING  checkIfCustomerHasBookings TO RETURN A RESULT
      // TODO add your handling code here:
    }//GEN-LAST:event_bookingsByCustomerButtonMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void a3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcertUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a10Button;
    private javax.swing.JButton a1Button;
    private javax.swing.JButton a2Button;
    private javax.swing.JButton a3Button;
    private javax.swing.JButton a4Button;
    private javax.swing.JButton a5Button;
    private javax.swing.JButton a6Button;
    private javax.swing.JButton a7Button;
    private javax.swing.JButton a8Button;
    private javax.swing.JButton a9Button;
    private javax.swing.JButton b10Button;
    private javax.swing.JButton b1Button;
    private javax.swing.JButton b2Button;
    private javax.swing.JButton b3Button;
    private javax.swing.JButton b4Button;
    private javax.swing.JButton b5Button;
    private javax.swing.JButton b6Button;
    private javax.swing.JButton b7Button;
    private javax.swing.JButton b8Button;
    private javax.swing.JButton b9Button;
    private javax.swing.JButton bookingsByCustomerButton;
    private javax.swing.JButton c10Button;
    private javax.swing.JButton c1Button;
    private javax.swing.JButton c2Button;
    private javax.swing.JButton c3Button;
    private javax.swing.JButton c4Button;
    private javax.swing.JButton c5Button;
    private javax.swing.JButton c6Button;
    private javax.swing.JButton c7Button;
    private javax.swing.JButton c8Button;
    private javax.swing.JButton c9Button;
    private javax.swing.JButton checkIfBookedButton;
    private javax.swing.JButton d10Button;
    private javax.swing.JButton d1Button;
    private javax.swing.JButton d2Button;
    private javax.swing.JButton d3Button;
    private javax.swing.JButton d4Button;
    private javax.swing.JButton d5Button;
    private javax.swing.JButton d6Button;
    private javax.swing.JButton d7Button;
    private javax.swing.JButton d8Button;
    private javax.swing.JButton d9Button;
    private javax.swing.JButton e10Button;
    private javax.swing.JButton e1Button;
    private javax.swing.JButton e2Button;
    private javax.swing.JButton e3Button;
    private javax.swing.JButton e4Button;
    private javax.swing.JButton e5Button;
    private javax.swing.JButton e6Button;
    private javax.swing.JButton e7Button;
    private javax.swing.JButton e8Button;
    private javax.swing.JButton e9Button;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton f10Button;
    private javax.swing.JButton f1Button;
    private javax.swing.JButton f2Button;
    private javax.swing.JButton f3Button;
    private javax.swing.JButton f4Button;
    private javax.swing.JButton f5Button;
    private javax.swing.JButton f6Button;
    private javax.swing.JButton f7Button;
    private javax.swing.JButton f8Button;
    private javax.swing.JButton f9Button;
    private javax.swing.JButton g10Button;
    private javax.swing.JButton g1Button;
    private javax.swing.JButton g2Button;
    private javax.swing.JButton g3Button;
    private javax.swing.JButton g4Button;
    private javax.swing.JButton g5Button;
    private javax.swing.JButton g6Button;
    private javax.swing.JButton g7Button;
    private javax.swing.JButton g8Button;
    private javax.swing.JButton g9Button;
    private javax.swing.JButton h10Button;
    private javax.swing.JButton h1Button;
    private javax.swing.JButton h2Button;
    private javax.swing.JButton h3Button;
    private javax.swing.JButton h4Button;
    private javax.swing.JButton h5Button;
    private javax.swing.JButton h6Button;
    private javax.swing.JButton h7Button;
    private javax.swing.JButton h8Button;
    private javax.swing.JButton h9Button;
    private javax.swing.JButton i10Button;
    private javax.swing.JButton i1Button;
    private javax.swing.JButton i2Button;
    private javax.swing.JButton i3Button;
    private javax.swing.JButton i4Button;
    private javax.swing.JButton i5Button;
    private javax.swing.JButton i6Button;
    private javax.swing.JButton i7Button;
    private javax.swing.JButton i8Button;
    private javax.swing.JButton i9Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton newConcertButton;
    private javax.swing.JButton setBronzePriceButton;
    private javax.swing.JButton setPriceGoldButton;
    private javax.swing.JButton setPriceSliverButton;
    // End of variables declaration//GEN-END:variables
}
