/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concertbooking;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JButton;


/**
 *
 * @author b00687749
 */
public class ConcertUI extends javax.swing.JFrame {

    /**
     * Creates new form ConcertUI
     */
    private double _bronzePrice =0;
    private double _silverPrice =0;
    private double _goldPrice =0;
   
    
    public double getGoldPrice(){
        return _goldPrice;
    }
    public double getSilverPrice(){
        return _silverPrice;
    }
    public double getBronzePrice(){
        return _bronzePrice;
    }
    
    
    
    public ConcertUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        newConcertButton = new javax.swing.JButton();
        setBronzePriceButton = new javax.swing.JButton();
        setPriceSliverButton = new javax.swing.JButton();
        setPriceGoldButton = new javax.swing.JButton();
        checkIfBookedButton = new javax.swing.JButton();
        bookingsByCustomerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        a01 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        a02 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        c01 = new javax.swing.JButton();
        c02 = new javax.swing.JButton();
        a04 = new javax.swing.JButton();
        a05 = new javax.swing.JButton();
        b03 = new javax.swing.JButton();
        b04 = new javax.swing.JButton();
        b05 = new javax.swing.JButton();
        a03 = new javax.swing.JButton();
        c04 = new javax.swing.JButton();
        c05 = new javax.swing.JButton();
        c03 = new javax.swing.JButton();
        b06 = new javax.swing.JButton();
        c09 = new javax.swing.JButton();
        a07 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        b07 = new javax.swing.JButton();
        c08 = new javax.swing.JButton();
        c06 = new javax.swing.JButton();
        c07 = new javax.swing.JButton();
        a09 = new javax.swing.JButton();
        a10 = new javax.swing.JButton();
        b08 = new javax.swing.JButton();
        b09 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        a06 = new javax.swing.JButton();
        a08 = new javax.swing.JButton();
        e01 = new javax.swing.JButton();
        d02 = new javax.swing.JButton();
        e02 = new javax.swing.JButton();
        f01 = new javax.swing.JButton();
        f02 = new javax.swing.JButton();
        d04 = new javax.swing.JButton();
        d05 = new javax.swing.JButton();
        e03 = new javax.swing.JButton();
        e04 = new javax.swing.JButton();
        e05 = new javax.swing.JButton();
        d01 = new javax.swing.JButton();
        d03 = new javax.swing.JButton();
        f04 = new javax.swing.JButton();
        f05 = new javax.swing.JButton();
        f03 = new javax.swing.JButton();
        e06 = new javax.swing.JButton();
        d07 = new javax.swing.JButton();
        e07 = new javax.swing.JButton();
        f06 = new javax.swing.JButton();
        f07 = new javax.swing.JButton();
        d09 = new javax.swing.JButton();
        d10 = new javax.swing.JButton();
        e08 = new javax.swing.JButton();
        e09 = new javax.swing.JButton();
        e10 = new javax.swing.JButton();
        d06 = new javax.swing.JButton();
        d08 = new javax.swing.JButton();
        f09 = new javax.swing.JButton();
        f10 = new javax.swing.JButton();
        f08 = new javax.swing.JButton();
        h01 = new javax.swing.JButton();
        g02 = new javax.swing.JButton();
        h02 = new javax.swing.JButton();
        i01 = new javax.swing.JButton();
        i02 = new javax.swing.JButton();
        g04 = new javax.swing.JButton();
        g05 = new javax.swing.JButton();
        h03 = new javax.swing.JButton();
        h04 = new javax.swing.JButton();
        h05 = new javax.swing.JButton();
        g01 = new javax.swing.JButton();
        g03 = new javax.swing.JButton();
        i04 = new javax.swing.JButton();
        i05 = new javax.swing.JButton();
        i03 = new javax.swing.JButton();
        h06 = new javax.swing.JButton();
        g07 = new javax.swing.JButton();
        h07 = new javax.swing.JButton();
        i06 = new javax.swing.JButton();
        i07 = new javax.swing.JButton();
        g09 = new javax.swing.JButton();
        g10 = new javax.swing.JButton();
        h08 = new javax.swing.JButton();
        h09 = new javax.swing.JButton();
        h10 = new javax.swing.JButton();
        g06 = new javax.swing.JButton();
        g08 = new javax.swing.JButton();
        i09 = new javax.swing.JButton();
        i10 = new javax.swing.JButton();
        i08 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel5.setText("   1        2       3        4        5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newConcertButton.setText("New Concert");
        newConcertButton.setToolTipText("");
        newConcertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConcertButtonActionPerformed(evt);
            }
        });

        setBronzePriceButton.setText("Set Price Bronze");
        setBronzePriceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setBronzePriceButtonMouseClicked(evt);
            }
        });
        setBronzePriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBronzePriceButtonActionPerformed(evt);
            }
        });

        setPriceSliverButton.setText("Set Price Sliver");
        setPriceSliverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPriceSliverButtonMouseClicked(evt);
            }
        });

        setPriceGoldButton.setText("Set Price Gold");
        setPriceGoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPriceGoldButtonActionPerformed(evt);
            }
        });

        checkIfBookedButton.setText("Check if Booked");
        checkIfBookedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkIfBookedButtonMouseClicked(evt);
            }
        });

        bookingsByCustomerButton.setText("Bookings By Customer");
        bookingsByCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsByCustomerButtonMouseClicked(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        a01.setBackground(new java.awt.Color(255, 204, 0));
        a01.setForeground(new java.awt.Color(255, 204, 0));
        a01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });
        a01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a01ActionPerformed(evt);
            }
        });

        b01.setBackground(new java.awt.Color(255, 204, 0));
        b01.setForeground(new java.awt.Color(255, 204, 0));
        b01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a02.setBackground(new java.awt.Color(255, 204, 0));
        a02.setForeground(new java.awt.Color(255, 204, 0));
        a02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b02.setBackground(new java.awt.Color(255, 204, 0));
        b02.setForeground(new java.awt.Color(255, 204, 0));
        b02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c01.setBackground(new java.awt.Color(255, 204, 0));
        c01.setForeground(new java.awt.Color(255, 204, 0));
        c01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c02.setBackground(new java.awt.Color(255, 204, 0));
        c02.setForeground(new java.awt.Color(255, 204, 0));
        c02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a04.setBackground(new java.awt.Color(255, 204, 0));
        a04.setForeground(new java.awt.Color(255, 204, 0));
        a04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a05.setBackground(new java.awt.Color(255, 204, 0));
        a05.setForeground(new java.awt.Color(255, 204, 0));
        a05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b03.setBackground(new java.awt.Color(255, 204, 0));
        b03.setForeground(new java.awt.Color(255, 204, 0));

        b04.setBackground(new java.awt.Color(255, 204, 0));
        b04.setForeground(new java.awt.Color(255, 204, 0));
        b04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b05.setBackground(new java.awt.Color(255, 204, 0));
        b05.setForeground(new java.awt.Color(255, 204, 0));
        b05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a03.setBackground(new java.awt.Color(255, 204, 0));
        a03.setForeground(new java.awt.Color(255, 204, 0));
        a03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c04.setBackground(new java.awt.Color(255, 204, 0));
        c04.setForeground(new java.awt.Color(255, 204, 0));
        c04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c05.setBackground(new java.awt.Color(255, 204, 0));
        c05.setForeground(new java.awt.Color(255, 204, 0));
        c05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c03.setBackground(new java.awt.Color(255, 204, 0));
        c03.setForeground(new java.awt.Color(255, 204, 0));
        c03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b06.setBackground(new java.awt.Color(255, 204, 0));
        b06.setForeground(new java.awt.Color(255, 204, 0));
        b06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c09.setBackground(new java.awt.Color(255, 204, 0));
        c09.setForeground(new java.awt.Color(255, 204, 0));
        c09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a07.setBackground(new java.awt.Color(255, 204, 0));
        a07.setForeground(new java.awt.Color(255, 204, 0));
        a07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c10.setBackground(new java.awt.Color(255, 204, 0));
        c10.setForeground(new java.awt.Color(255, 204, 0));
        c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b07.setBackground(new java.awt.Color(255, 204, 0));
        b07.setForeground(new java.awt.Color(255, 204, 0));
        b07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c08.setBackground(new java.awt.Color(255, 204, 0));
        c08.setForeground(new java.awt.Color(255, 204, 0));
        c08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c06.setBackground(new java.awt.Color(255, 204, 0));
        c06.setForeground(new java.awt.Color(255, 204, 0));
        c06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        c07.setBackground(new java.awt.Color(255, 204, 0));
        c07.setForeground(new java.awt.Color(255, 204, 0));
        c07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a09.setBackground(new java.awt.Color(255, 204, 0));
        a09.setForeground(new java.awt.Color(255, 204, 0));
        a09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a10.setBackground(new java.awt.Color(255, 204, 0));
        a10.setForeground(new java.awt.Color(255, 204, 0));
        a10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b08.setBackground(new java.awt.Color(255, 204, 0));
        b08.setForeground(new java.awt.Color(255, 204, 0));
        b08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b09.setBackground(new java.awt.Color(255, 204, 0));
        b09.setForeground(new java.awt.Color(255, 204, 0));
        b09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        b10.setBackground(new java.awt.Color(255, 204, 0));
        b10.setForeground(new java.awt.Color(255, 204, 0));
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a06.setBackground(new java.awt.Color(255, 204, 0));
        a06.setForeground(new java.awt.Color(255, 204, 0));
        a06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        a08.setBackground(new java.awt.Color(255, 204, 0));
        a08.setForeground(new java.awt.Color(255, 204, 0));
        a08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookGoldSeat(evt);
            }
        });

        e01.setBackground(new java.awt.Color(204, 204, 204));
        e01.setForeground(new java.awt.Color(204, 204, 204));

        d02.setBackground(new java.awt.Color(204, 204, 204));
        d02.setForeground(new java.awt.Color(204, 204, 204));

        e02.setBackground(new java.awt.Color(204, 204, 204));
        e02.setForeground(new java.awt.Color(204, 204, 204));

        f01.setBackground(new java.awt.Color(204, 204, 204));
        f01.setForeground(new java.awt.Color(204, 204, 204));

        f02.setBackground(new java.awt.Color(204, 204, 204));
        f02.setForeground(new java.awt.Color(204, 204, 204));

        d04.setBackground(new java.awt.Color(204, 204, 204));
        d04.setForeground(new java.awt.Color(204, 204, 204));

        d05.setBackground(new java.awt.Color(204, 204, 204));
        d05.setForeground(new java.awt.Color(204, 204, 204));

        e03.setBackground(new java.awt.Color(204, 204, 204));
        e03.setForeground(new java.awt.Color(204, 204, 204));

        e04.setBackground(new java.awt.Color(204, 204, 204));
        e04.setForeground(new java.awt.Color(204, 204, 204));

        e05.setBackground(new java.awt.Color(204, 204, 204));
        e05.setForeground(new java.awt.Color(204, 204, 204));

        d01.setBackground(new java.awt.Color(204, 204, 204));
        d01.setForeground(new java.awt.Color(204, 204, 204));

        d03.setBackground(new java.awt.Color(204, 204, 204));
        d03.setForeground(new java.awt.Color(204, 204, 204));

        f04.setBackground(new java.awt.Color(204, 204, 204));
        f04.setForeground(new java.awt.Color(204, 204, 204));

        f05.setBackground(new java.awt.Color(204, 204, 204));
        f05.setForeground(new java.awt.Color(204, 204, 204));

        f03.setBackground(new java.awt.Color(204, 204, 204));
        f03.setForeground(new java.awt.Color(204, 204, 204));

        e06.setBackground(new java.awt.Color(204, 204, 204));
        e06.setForeground(new java.awt.Color(204, 204, 204));

        d07.setBackground(new java.awt.Color(204, 204, 204));
        d07.setForeground(new java.awt.Color(204, 204, 204));

        e07.setBackground(new java.awt.Color(204, 204, 204));
        e07.setForeground(new java.awt.Color(204, 204, 204));

        f06.setBackground(new java.awt.Color(204, 204, 204));
        f06.setForeground(new java.awt.Color(204, 204, 204));

        f07.setBackground(new java.awt.Color(204, 204, 204));
        f07.setForeground(new java.awt.Color(204, 204, 204));

        d09.setBackground(new java.awt.Color(204, 204, 204));
        d09.setForeground(new java.awt.Color(204, 204, 204));

        d10.setBackground(new java.awt.Color(204, 204, 204));
        d10.setForeground(new java.awt.Color(204, 204, 204));

        e08.setBackground(new java.awt.Color(204, 204, 204));
        e08.setForeground(new java.awt.Color(204, 204, 204));

        e09.setBackground(new java.awt.Color(204, 204, 204));
        e09.setForeground(new java.awt.Color(204, 204, 204));

        e10.setBackground(new java.awt.Color(204, 204, 204));
        e10.setForeground(new java.awt.Color(204, 204, 204));

        d06.setBackground(new java.awt.Color(204, 204, 204));
        d06.setForeground(new java.awt.Color(204, 204, 204));

        d08.setBackground(new java.awt.Color(204, 204, 204));
        d08.setForeground(new java.awt.Color(204, 204, 204));

        f09.setBackground(new java.awt.Color(204, 204, 204));
        f09.setForeground(new java.awt.Color(204, 204, 204));

        f10.setBackground(new java.awt.Color(204, 204, 204));
        f10.setForeground(new java.awt.Color(204, 204, 204));

        f08.setBackground(new java.awt.Color(204, 204, 204));
        f08.setForeground(new java.awt.Color(204, 204, 204));

        h01.setBackground(new java.awt.Color(102, 51, 0));
        h01.setForeground(new java.awt.Color(102, 51, 0));

        g02.setBackground(new java.awt.Color(102, 51, 0));
        g02.setForeground(new java.awt.Color(102, 51, 0));

        h02.setBackground(new java.awt.Color(102, 51, 0));
        h02.setForeground(new java.awt.Color(102, 51, 0));

        i01.setBackground(new java.awt.Color(102, 51, 0));
        i01.setForeground(new java.awt.Color(102, 51, 0));

        i02.setBackground(new java.awt.Color(102, 51, 0));
        i02.setForeground(new java.awt.Color(102, 51, 0));

        g04.setBackground(new java.awt.Color(102, 51, 0));
        g04.setForeground(new java.awt.Color(102, 51, 0));

        g05.setBackground(new java.awt.Color(102, 51, 0));
        g05.setForeground(new java.awt.Color(102, 51, 0));

        h03.setBackground(new java.awt.Color(102, 51, 0));
        h03.setForeground(new java.awt.Color(102, 51, 0));

        h04.setBackground(new java.awt.Color(102, 51, 0));
        h04.setForeground(new java.awt.Color(102, 51, 0));

        h05.setBackground(new java.awt.Color(102, 51, 0));
        h05.setForeground(new java.awt.Color(102, 51, 0));

        g01.setBackground(new java.awt.Color(102, 51, 0));
        g01.setForeground(new java.awt.Color(102, 51, 0));

        g03.setBackground(new java.awt.Color(102, 51, 0));
        g03.setForeground(new java.awt.Color(102, 51, 0));

        i04.setBackground(new java.awt.Color(102, 51, 0));
        i04.setForeground(new java.awt.Color(102, 51, 0));

        i05.setBackground(new java.awt.Color(102, 51, 0));
        i05.setForeground(new java.awt.Color(102, 51, 0));

        i03.setBackground(new java.awt.Color(102, 51, 0));
        i03.setForeground(new java.awt.Color(102, 51, 0));

        h06.setBackground(new java.awt.Color(102, 51, 0));
        h06.setForeground(new java.awt.Color(102, 51, 0));

        g07.setBackground(new java.awt.Color(102, 51, 0));
        g07.setForeground(new java.awt.Color(102, 51, 0));

        h07.setBackground(new java.awt.Color(102, 51, 0));
        h07.setForeground(new java.awt.Color(102, 51, 0));

        i06.setBackground(new java.awt.Color(102, 51, 0));
        i06.setForeground(new java.awt.Color(102, 51, 0));

        i07.setBackground(new java.awt.Color(102, 51, 0));
        i07.setForeground(new java.awt.Color(102, 51, 0));

        g09.setBackground(new java.awt.Color(102, 51, 0));
        g09.setForeground(new java.awt.Color(102, 51, 0));

        g10.setBackground(new java.awt.Color(102, 51, 0));
        g10.setForeground(new java.awt.Color(102, 51, 0));

        h08.setBackground(new java.awt.Color(102, 51, 0));
        h08.setForeground(new java.awt.Color(102, 51, 0));

        h09.setBackground(new java.awt.Color(102, 51, 0));
        h09.setForeground(new java.awt.Color(102, 51, 0));

        h10.setBackground(new java.awt.Color(102, 51, 0));
        h10.setForeground(new java.awt.Color(102, 51, 0));

        g06.setBackground(new java.awt.Color(102, 51, 0));
        g06.setForeground(new java.awt.Color(102, 51, 0));

        g08.setBackground(new java.awt.Color(102, 51, 0));
        g08.setForeground(new java.awt.Color(102, 51, 0));

        i09.setBackground(new java.awt.Color(102, 51, 0));
        i09.setForeground(new java.awt.Color(102, 51, 0));
        i09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i09ActionPerformed(evt);
            }
        });

        i10.setBackground(new java.awt.Color(102, 51, 0));
        i10.setForeground(new java.awt.Color(102, 51, 0));

        i08.setBackground(new java.awt.Color(102, 51, 0));
        i08.setForeground(new java.awt.Color(102, 51, 0));

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));

        jLabel2.setText("Fire Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 51));

        jLabel3.setText("Fire Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setText("Stage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel4.setText("   1        2       3        4        5");

        jLabel6.setText("   6        7       8        9       10");

        jLabel7.setText("A");

        jLabel8.setText("B");

        jLabel9.setText("C");

        jLabel10.setText("D");

        jLabel11.setText("E");

        jLabel12.setText("F");

        jLabel13.setText("G");

        jLabel14.setText("H");

        jLabel15.setText("I");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newConcertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setBronzePriceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setPriceSliverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setPriceGoldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkIfBookedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingsByCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(165, 165, 165)
                                                            .addComponent(jLabel7))
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(g02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(i02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(f01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c03, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c05, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(f06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g06, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(g07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(h07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(i07, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i08, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i09, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newConcertButton)
                    .addComponent(setBronzePriceButton)
                    .addComponent(setPriceSliverButton)
                    .addComponent(setPriceGoldButton)
                    .addComponent(checkIfBookedButton)
                    .addComponent(bookingsByCustomerButton)
                    .addComponent(exitButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(d01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(d05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(e01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(e05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(f01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel12)))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(g01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(h01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(h05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(i01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i02, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i03, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i04, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i05, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel14)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c06, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c07, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c08, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c09, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newConcertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConcertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newConcertButtonActionPerformed

    private void i09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i09ActionPerformed

    private void a01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a01ActionPerformed

    private void setBronzePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBronzePriceButtonActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_setBronzePriceButtonActionPerformed

    private void setBronzePriceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setBronzePriceButtonMouseClicked
        String bronzePrice = JOptionPane.showInputDialog(null, "Set Price For Bronze Seating:");
        try{
            _bronzePrice = Double.valueOf(bronzePrice);
            JOptionPane.showMessageDialog(null, "The Price Has been set to £" + bronzePrice);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, value not accepted", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_setBronzePriceButtonMouseClicked

    private void setPriceSliverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPriceSliverButtonMouseClicked
        String silverPrice = JOptionPane.showInputDialog(null, "Set Price For Sliver Seating:");
        try{
            _silverPrice = Double.valueOf(silverPrice);
            JOptionPane.showMessageDialog(null, "The Price Has been set to £" + silverPrice);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, value not accepted", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_setPriceSliverButtonMouseClicked

    private void setPriceGoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPriceGoldButtonActionPerformed
        String goldPrice = JOptionPane.showInputDialog(null, "Set Price For Gold Seating:");
        try{
            _goldPrice = Double.valueOf(goldPrice);
            JOptionPane.showMessageDialog(null, "The Price Has been set to £" + goldPrice);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, value not accepted", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);
        }
       // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceGoldButtonActionPerformed

    private void checkIfBookedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkIfBookedButtonMouseClicked
        String checkIfBooked = JOptionPane.showInputDialog(null, "Enter the Seat You Would Like To Check");
        //ADD  AN IF SATEMENT USING CHECKIFBOOKED TO RETURN A RESULT
        // TODO add your handling code here:
    }//GEN-LAST:event_checkIfBookedButtonMouseClicked

    private void bookingsByCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsByCustomerButtonMouseClicked
      String checkIfCustomerHasBookings = JOptionPane.showInputDialog(null, "Enter a Customer Name");
//ADD A FOR SATEMENT USING  checkIfCustomerHasBookings TO RETURN A RESULT
      // TODO add your handling code here:
    }//GEN-LAST:event_bookingsByCustomerButtonMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void bookGoldSeat(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookGoldSeat
        // TODO add your handling code here:
        
        String purchaserName = JOptionPane.showInputDialog("Please enter the purchaser name:");
        if(purchaserName == null) { }
        else if(purchaserName.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid purchaser name.");
            bookGoldSeat(evt);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"This seat has been successfully booked by "+purchaserName);
            boolean hasBackstagePass = false;
            Random r = new Random();
            int chance = r.nextInt(11);
            if (chance == 2)
            {
                hasBackstagePass = true;
                JOptionPane.showMessageDialog(null,"The purchaser of this seat has one a backstage pass for tonights concert.");
            }
            evt.getComponent().setBackground(Color.red);
        }
    }//GEN-LAST:event_bookGoldSeat

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcertUI().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a01;
    private javax.swing.JButton a02;
    private javax.swing.JButton a03;
    private javax.swing.JButton a04;
    private javax.swing.JButton a05;
    private javax.swing.JButton a06;
    private javax.swing.JButton a07;
    private javax.swing.JButton a08;
    private javax.swing.JButton a09;
    private javax.swing.JButton a10;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b03;
    private javax.swing.JButton b04;
    private javax.swing.JButton b05;
    private javax.swing.JButton b06;
    private javax.swing.JButton b07;
    private javax.swing.JButton b08;
    private javax.swing.JButton b09;
    private javax.swing.JButton b10;
    private javax.swing.JButton bookingsByCustomerButton;
    private javax.swing.JButton c01;
    private javax.swing.JButton c02;
    private javax.swing.JButton c03;
    private javax.swing.JButton c04;
    private javax.swing.JButton c05;
    private javax.swing.JButton c06;
    private javax.swing.JButton c07;
    private javax.swing.JButton c08;
    private javax.swing.JButton c09;
    private javax.swing.JButton c10;
    private javax.swing.JButton checkIfBookedButton;
    private javax.swing.JButton d01;
    private javax.swing.JButton d02;
    private javax.swing.JButton d03;
    private javax.swing.JButton d04;
    private javax.swing.JButton d05;
    private javax.swing.JButton d06;
    private javax.swing.JButton d07;
    private javax.swing.JButton d08;
    private javax.swing.JButton d09;
    private javax.swing.JButton d10;
    private javax.swing.JButton e01;
    private javax.swing.JButton e02;
    private javax.swing.JButton e03;
    private javax.swing.JButton e04;
    private javax.swing.JButton e05;
    private javax.swing.JButton e06;
    private javax.swing.JButton e07;
    private javax.swing.JButton e08;
    private javax.swing.JButton e09;
    private javax.swing.JButton e10;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton f01;
    private javax.swing.JButton f02;
    private javax.swing.JButton f03;
    private javax.swing.JButton f04;
    private javax.swing.JButton f05;
    private javax.swing.JButton f06;
    private javax.swing.JButton f07;
    private javax.swing.JButton f08;
    private javax.swing.JButton f09;
    private javax.swing.JButton f10;
    private javax.swing.JButton g01;
    private javax.swing.JButton g02;
    private javax.swing.JButton g03;
    private javax.swing.JButton g04;
    private javax.swing.JButton g05;
    private javax.swing.JButton g06;
    private javax.swing.JButton g07;
    private javax.swing.JButton g08;
    private javax.swing.JButton g09;
    private javax.swing.JButton g10;
    private javax.swing.JButton h01;
    private javax.swing.JButton h02;
    private javax.swing.JButton h03;
    private javax.swing.JButton h04;
    private javax.swing.JButton h05;
    private javax.swing.JButton h06;
    private javax.swing.JButton h07;
    private javax.swing.JButton h08;
    private javax.swing.JButton h09;
    private javax.swing.JButton h10;
    private javax.swing.JButton i01;
    private javax.swing.JButton i02;
    private javax.swing.JButton i03;
    private javax.swing.JButton i04;
    private javax.swing.JButton i05;
    private javax.swing.JButton i06;
    private javax.swing.JButton i07;
    private javax.swing.JButton i08;
    private javax.swing.JButton i09;
    private javax.swing.JButton i10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton newConcertButton;
    private javax.swing.JButton setBronzePriceButton;
    private javax.swing.JButton setPriceGoldButton;
    private javax.swing.JButton setPriceSliverButton;
    // End of variables declaration//GEN-END:variables
}
